### ISSUE TITLE
Hi! got that Error when starting new campaign ^^

### ISSUE THREAD

**Issue by DraukaRalh** [mipen/BannerlordTweaks#105] opened 2020-05-09 04:01 UTC
![image](https://user-images.githubusercontent.com/65057603/81463551-46f0fe00-9188-11ea-8699-3648c775dac0.png)

**Comment by DraukaRalh** [comment] 2020-05-09 04:02
Recorded Unhandled Exceptions:
  1. System.ArgumentNullException: Value cannot be null.
    Parameter name: key
       at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at TaleWorlds.Core.PropertyOwner`1.SetPropertyValue(T attribute, Int32 value)
       at TaleWorlds.CampaignSystem.HeroDeveloper.AddFocus(SkillObject skill, Int32 changeAmount, Boolean checkUnspentFocusPoints)
       at TaleWorlds.CampaignSystem.SandBox.CampaignBehaviors.Towns.CharacterDevelopmentCampaignBehaivor.DistributeUnspentFocusPoints(Hero hero)
       at TaleWorlds.CampaignSystem.SandBox.CampaignBehaviors.Towns.CharacterDevelopmentCampaignBehaivor.CampaignStart()
       at TaleWorlds.CampaignSystem.MbEvent.InvokeList(EventHandlerRec list)
       at TaleWorlds.CampaignSystem.CampaignEvents.OnNewGameCreated5()
       at TaleWorlds.CampaignSystem.CampaignEventDispatcher.OnNewGameCreated5()
       at TaleWorlds.CampaignSystem.Campaign.OnNewGameCreated(CampaignGameStarter starter)
       at TaleWorlds.CampaignSystem.Campaign.OnGameCreated(CampaignGameStarter gameStarter)
       at TaleWorlds.CampaignSystem.Campaign.DoLoadingForGameType(GameTypeLoadingStates gameTypeLoadingState, GameTypeLoadingStates& nextState)
       at StoryMode.CampaignStoryMode.DoLoadingForGameType(GameTypeLoadingStates gameTypeLoadingState, GameTypeLoadingStates& nextState)
       at TaleWorlds.Core.GameType.DoLoadingForGameType()
       at StoryMode.StoryModeGameManager.DoLoadingForGameManager(GameManagerLoadingSteps gameManagerLoadingStep, GameManagerLoadingSteps& nextStep)
       at TaleWorlds.Core.GameManagerBase.DoLoadingForGameManager()
       at TaleWorlds.MountAndBlade.GameLoadingState.OnTick(Single dt)
       at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
       at DMD<DMD<OnApplicationTick_Patch1>?1588383::OnApplicationTick_Patch1>(Module this, Single dt)
       at TaleWorlds.DotNet.Managed.ApplicationTick(Single dt)
       at DMD<DMD<Managed_ApplicationTick_Patch1>?8714086::Managed_ApplicationTick_Patch1>(Single dt)

Recorded First Chance Exceptions:
  Recording disabled.

Modules Information:
  1. !DCC v1.0.0.228624
    *DCC Main* (Required) (!DCC)
  2. CharacterTrainer v1.0.11.228624
    Character Trainer (CharacterTrainer)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  3. CombatModCollection v1.4.0.228624
    Combat Mod Collection (CombatModCollection)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. StoryMode
    5. CustomBattle
  4. CommunityPatch v0.0.2.228624
    Community Patch (CommunityPatch)
  5. CultureChanger v1.0.0.228624
    Culture Changer (CultureChanger)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  6. CustomBattle e1.3.1.228624 *Selected*
    CustomBattle (CustomBattle) *Official*
  Dependencies:
    1. Native
    2. SandBoxCore
  7. CustomTroopUpgrades v0.3.2.228624
    Custom Troop Upgrade And Replacer Mod (CustomTroopUpgrades)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  8. DistinguishedService v1.0.0.228624
    Distinguished Service (Debug)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. StoryMode
  9. DeveloperConsole v1.3.2.228624
    Developer Console (DeveloperConsole)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  10. DiplomacyFixes v1.1.2.228624
    Diplomacy Fixes (DiplomacyFixes)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  11. DistinguishedService v1.0.0.228624
    Distinguished Service (DistinguishedService)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. StoryMode
  12. EditLord v1.4.7.228624
    Edit Lord (EditLord)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  13. EquipmentUpgrader v1.0.2.228624
    EquipmentUpgrader (EquipmentUpgrader)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  14. HealthRebalance v1.1.0.228624
    Health Rebalance (HealthRebalance)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. StoryMode
  15. ImprovedGarrisons v3.0.4.2
    Improved Garrisons (ImprovedGarrisons)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  16. KingdomColor v1.4.0.228624
    KingdomColor (KingdomColor)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  17. MBFastDialogue v2.4.0.228624
    MBFastDialogue (MBFastDialogue)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  18. ModLib v1.3.4.228624
    ModLib (ModLib)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  19. MoreTroops v1.1.0.228624
    Complete Troop Overhaul (MoreTroops)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. StoryMode
  20. Native e1.3.1.228624 *Selected*
    Native (Native) *Official*
  21. NPCRevamp v9.0.0.228624
    NPC Revamp (NPCRevamp)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  22. DistinguishedService v1.0.0.228624
    Distinguished Service (other)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. StoryMode
  23. PersistentLock v1.0.0.228624
    Persistent Lock (PersistentLock)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  24. RealisticBattle v1.1.2.228624
    Realistic Battle with more armor (RealisticBattle)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  25. Sandbox e1.3.1.228624 *Selected*
    Sandbox (SandBox) *Official*
  Dependencies:
    1. Native
    2. SandBoxCore
  26. SandBoxCore e1.3.1.228624 *Selected*
    SandBox Core (SandBoxCore) *Official*
  Dependencies:
    1. Native
  27. Separatism v0.4.4.228624
    Separatism (Separatism)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  28. StoryMode e1.3.1.228624 *Selected*
    StoryMode (StoryMode) *Official*
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
  29. Telepathy v0.3.1.228624
    Telepathy (Telepathy)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  30. zCulturedStart v1.1.10.228624
    zCulturedStart (zCulturedStart)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  31. zExpandedBandits v0.0.9.228624
    zExpandedBandits (zExpandedBandits)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  32. zzBannerlordTweaks v1.3.4.228624
    Bannerlord Tweaks (zzBannerlordTweaks)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
    6. ModLib
  33. zzCharacterCreation v1.1.2.228624
    Detailed Character Creation (zzCharacterCreation)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode

Community Patch Information:
  1. ItemComparisonColorPatch *Active* *Applicable* *Applied*
  2. LearningRateExplainerPatch *Active* *Applicable* *Applied*
  3. LordConversationsCampaignBehaviorPatch *Active* *Applied*
  4. MapFactionLogicLoopPatch
  5. MaxFoodVarietyPartyMoralePatch
  6. NeutralClanTierUpPatch *Active* *Applicable* *Applied*
  7. ProsperousReignPatch *Active* *Applicable* *Applied*
  8. LandGrantsForVeteransPatch
  9. DisciplinarianPatch
  10. AgrarianPatch *Active* *Applied*
  11. AgriculturePatch *Active* *Applicable* *Applied*
  12. AssessorPatch *Active* *Applicable* *Applied*
  13. BannerlordPatch
  14. EnhancedMinesPatch *Active* *Applicable* *Applied*
  15. FoodRationingPatch
  16. LogisticsExpertPatch *Active* *Applicable* *Applied*
  17. ManAtArmsPatch
  18. NourishSettlementPatch
  19. ProminencePatch *Active* *Applicable* *Applied*
  20. ReconstructionPatch *Active* *Applicable* *Applied*
  21. ReevePatch *Active* *Applicable* *Applied*
  22. RulerPatch *Active* *Applicable* *Applied*
  23. SwordsAsTributePatch
  24. TaxCollectorPatch *Active* *Applicable* *Applied*
  25. SupremeAuthorityPatch *Active* *Applicable* *Applied*
  26. WarmongerPatch *Active* *Applicable* *Applied*
  27. WarRationsPatch *Active* *Applicable* *Applied*
  28. BowExpertPatch *Active* *Applicable* *Applied*
  29. ConroiPatch
  30. CrossbowExpert *Active* *Applicable* *Applied*
  31. FilledToBrimPatch *Active* *Applicable* *Applied*
  32. SpareArrowsPatch *Active* *Applicable* *Applied*
  33. SpareThrowingWeapon *Active* *Applicable* *Applied*
  34. SquiresPatch
  35. ExtraArrowsPatch *Active* *Applicable* *Applied*
  36. ExtraThrowingWeapons *Active* *Applicable* *Applied*
  37. PeakFormPatch *Active* *Maybe Applicable* *Applied*
  38. HealthyScoutPatch *Active* *Maybe Applicable* *Applied*
  39. BattleReadyPatch *Active* *Applicable* *Applied*
  40. FullyArmedPatch *Active* *Applicable* *Applied*
  41. CrossbowCavalryPerkPatch *Active* *Applicable* *Applied*
  42. BattleEquippedPatch *Active* *Applicable* *Applied*
  43. BowMountedArcherPatch *Active* *Applicable* *Applied*
  44. LargeQuiverPatch *Active* *Applicable* *Applied*

Loaded SubModules:
  1. TaleWorlds.MountAndBlade.View.ViewSubModule, TaleWorlds.MountAndBlade.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  2. TaleWorlds.MountAndBlade.GauntletUI.GauntletUISubModule, TaleWorlds.MountAndBlade.GauntletUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  3. TaleWorlds.MountAndBlade.CustomBattle.CustomBattleSubModule, TaleWorlds.MountAndBlade.CustomBattle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  4. SandBox.SandBoxSubModule, SandBox, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  5. SandBox.View.SandBoxViewSubModule, SandBox.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  6. SandBox.GauntletUI.SandBoxGauntletUISubModule, SandBox.GauntletUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  7. StoryMode.StoryModeSubModule, StoryMode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  8. StoryMode.View.StoryModeViewSubModule, StoryMode.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  9. StoryMode.GauntletUI.StoryModeGauntletUISubModule, StoryMode.GauntletUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  10. ModLib.ModLibSubModule, ModLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  11. ModLib.Patches.ModLibPatchesSubModule, ModLib.Patches, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  12. CharacterCreation.SubModule, CharacterCreation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  13. MBOptionScreen.MBOptionScreenSubModule, MBOptionScreen, Version=1.1.15.0, Culture=neutral, PublicKeyToken=null
    v1.1.15
  14. CommunityPatch.CommunityPatchSubModule, CommunityPatch, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null
    v0.1.0+3238ab7
  15. CustomTroopUpgrades.CustomTroopUpgradesCore, CustomTroopUpgrades, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  16. DistinguishedService.SubModule, DistinguishedService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  17. HealthRebalance.CustomCharacterStatsMain, HealthRebalance, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  18. CharacterTrainer.SubModule, CharacterTrainer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  19. CultureChanger.Main, CultureChanger, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  20. DeveloperConsole.SubModule, DeveloperConsole, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  21. DiplomacyFixes.MySubModule, DiplomacyFixes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  22. MBOptionScreen.MBOptionScreenSubModuleV2010, MBOptionScreen.v2.0.10, Version=2.0.10.0, Culture=neutral, PublicKeyToken=null
    v2.0.10
  23. EditLord.Main, EditLord, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null
  24. EquipmentUpgrader.EquipmentUpgraderSubModule, EquipmentUpgrader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  25. ImprovedGarrisons.Main, ImprovedGarrisons, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  26. KingdomColor.KingdomColorModule, KingdomColor, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null
  27. MBFastDialogue.FastDialogueSubModule, MBFastDialogue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  28. PersistentLock.SubModule, PersistentLock, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  29. Separatism.SeparatismSubModule, Separatism, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  30. Telepathy.TelepathySubModule, Telepathy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  31. zCulturedStart.SubModule, zCulturedStart, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  32. BannerlordTweaks.SubModule, BannerlordTweaks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  33. CombatModCollection.SubModule, CombatModCollection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    v1.0.0
  34. RealisticBattle.Main, RealisticBattle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System Info:
  gpu: NVIDIA GeForce GTX 1080 Ti
  cpu: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
  
  GPU Memory: 11127MB
  GC Allocated: 129218048B
  Engine Memory Used: 0MB
  GC Latency Mode: Client Interactive
  GC LOH Compact Mode: Default
  Operating System: Microsoft Windows 10.0.18363 
  Framework Compatibility: .NET Framework 4.8.4121.0
  Hardware Accelerated Vector: Yes
  Vector Size: 256 bits
  CPU Info:
    1. Intel Core i5-9600K with 6 cores:
      1. (?) MHz (?) °C
      2. (?) MHz (?) °C
      3. (?) MHz (?) °C
      4. (?) MHz (?) °C
      5. (?) MHz (?) °C
      6. (?) MHz (?) °C

Got that if it's help

**Comment by wfswanepoel** [comment] 2020-05-09 19:23
You do realise that half the mods that you have listed are not compatible with Stable version 1.3.1 and BETA 1.4.0 ?
 For example:

!DCC v1.0.0.228624
DCC Main (Required) (!DCC)
CharacterTrainer v1.0.11.228624
and COmmunity Patch 

REMOVE every single mod out of your modules folder. Do not disable it, it must be taken out of the modules folder.
Add only Modlib and BannerlordTweaks, configure it correctly. Start your game and start a clean new campaign.

I tested beta 1.4.0 and stable 1.3.1 and 1.3.0, all works perfectly.

**Comment by DraukaRalh** [comment] 2020-05-09 19:31
oh ok il'l see to that thx for the tip

**Comment by mipen** [comment] 2020-05-11 01:10
The original error is a duplicate of #106. Fixed in commit 7b196c95dfafc8fcb99a4f919c87a8c8024390e8 for base version and f1d721333f60227f77eef0e9e90d654578669ff6 for beta version.

**Closed** 2020-05-11 01:10 UTC
