### ISSUE TITLE
HideOut Battle Tweaks

### ISSUE THREAD

**Issue by fragtzack** [mipen/BannerlordTweaks#26] opened 2020-04-08 21:48 UTC
The 2 boolean values in Hideout Battle Tweaks are not accurate to the text in GUI.

Check marked "Continue HideOut Battle On Player Death" sets the  XML value to :

<LoseHideoutBattleOnPlayerDeath>true</LoseHideoutBattleOnPlayerDeath>

This XML value should be set to >false< if check marked in GUI.

Same issue for the other boolean in Hideout Battle Tweaks

**Comment by ajvr** [comment] 2020-04-08 22:38
I think this is a duplicate of #24

**Comment by mipen** [comment] 2020-04-09 05:49
Fixed in update 1.1.1

**Closed** 2020-04-09 05:48 UTC
