### ISSUE TITLE
Crash (related to focus/attribute) when creating a new campaign

### ISSUE THREAD

**Issue by Koolenjoy** [mipen/BannerlordTweaks#106] opened 2020-05-09 12:08 UTC
Hi, 

When i tried to create a new campaign(1.4 beta, only mods were Modlib and Bannerlord tweaks) the game crashed. I found that it was because of the tweaks i did to attribute per level (it was set to 1/level) and focus points (3/level).
If the tweak was still enabled but values were the default ones (3level/attribute and 1/focus) i could start a new campaign. 
Changing the values after the campaign start is possible and works, but it seems to create crashes.

Awesome work on this mod btw !

**Comment by koyteck** [comment] 2020-05-09 17:16
same
![image](https://user-images.githubusercontent.com/7686546/81480350-80c61100-9229-11ea-97cc-16820962c95f.png)

**Comment by wfswanepoel** [comment] 2020-05-09 19:09
I tested this right now with version 1.3.1 and on beta 1.4.0 and I do not get this error. so you are running a mod that is not compatible with the game that requires an update.

It might also be that you are using FixedLauncher, it seems a lot of people might have that issue with that launcher.

I am using https://www.nexusmods.com/mountandblade2bannerlord/mods/265 Bannerlord Mod Launcher.

here is my loadout:
https://imgur.com/a/efk4UTC

No errors at all. I tried it with Attributes 2 and 4

**Comment by koyteck** [comment] 2020-05-10 06:17
I didnt use any Launchers or Loaders. Are they necessary?
I know its time consuming, but my crashes started after 2-3h gameplay.
Only mods I am using are: Community Patch, Modlib and Bannerlord Tweaks.

**Comment by koyteck** [comment] 2020-05-10 17:50
I deleted every file game, save and mod.
Made new instalation (1.3.1) with only mods like bannerpaste, communitypatch, modlib and bannerlord tweaks. Everything was fine for about 3-4 hours than crash and message like above.
Most tweaks was off, but atribute tweak was on with config 2/4.
Please look into it.

**Comment by mipen** [comment] 2020-05-10 23:51
This is the result of a native bug. In an unmodded game it would eventually happen after a very long time, but increasing the amount of focus points gained per level means it happens sooner. What's happening is that when npc lords are in a town, any focus points they have gained from levels are spent on their skills. The problem is that there is a weighted function that is used to determine which skills to add focus points to, but it will eventually return null when all the lord's skills are at a high focus point investment. This is what is causing the error. It might not ever actually happen in native as the lord wouldn't be able to get to a high enough level to get enough focus points to cause the error. The next version of the mod will include a patch which should fix the error for now, and I'll report it to TW so they can fix it on their end.

**Comment by mipen** [comment] 2020-05-11 01:09
Fixed in commit 7b196c95dfafc8fcb99a4f919c87a8c8024390e8 for base version and 
f1d721333f60227f77eef0e9e90d654578669ff6 for beta version.

**Closed by mipen** 2020-05-11 01:09 UTC
